[package]
name = "dice-wire-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = [ "api-4-2" ] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
